#-------# step :1----------#

In [1]:
# importing labiries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

#-------# step :2 #--------#
        #loading the data_set

In [2]:
data_set = pd.read_csv("Churn_Modelling.csv")

In [3]:
data_set.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,3,15619304,Onio,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,4,15701354,Boni,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

#--------#step:3 #-------#

#data prepcocessing

In [4]:
# droping the inrelivent coloum from data set

In [5]:
data_set = data_set.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [6]:
data_set.head(5)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,Female,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,Female,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,Female,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,Female,43.0,2,125510.82,1,NaN,1.0,79084.10,0

In [7]:
# encoding the categoral coloum from my data_set

In [8]:
LB = LabelEncoder()

In [9]:
data_set['Gender'] = LB.fit_transform(data_set['Gender'])

In [10]:
data_set

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42.0,2,0.00,1,1.0,1.0,101348.88,1
1,608,Spain,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0
2,502,France,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1
3,699,France,0,39.0,1,0.00,2,0.0,0.0,93826.63,0
4,850,Spain,0,43.0,2,125510.82,1,NaN,1.0,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9997,709,France,0,36.0,7,0.00,1,0.0,1.0,42085.58,1
9998,772,Germany,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1
9999,772,Germany,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1
10000,792,France,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0
10001,792,France,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0

In [11]:
# 0 = FEMALE
#1 = MALE

In [12]:
# so we have one more coloum callled geography , for that we are using an onelot encoder becuse we having 3 catagires .
# if we use labeal encoding it will assign 1,2,3 for three features (france,germoney,spain) but ann things as a number so toslove that we are using onehot
#encoding

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

onehot_encoder_geo = OneHotEncoder()

geo_encoded = onehot_encoder_geo.fit_transform(data_set[['Geography']])

geo_encoded_df = pd.DataFrame(
    geo_encoded.toarray(),
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)

geo_encoded_df

       Geography_France  Geography_Germany  Geography_Spain  Geography_nan
0                   1.0                0.0              0.0            0.0
1                   0.0                0.0              1.0            0.0
2                   1.0                0.0              0.0            0.0
3                   1.0                0.0              0.0            0.0
4                   0.0                0.0              1.0            0.0
...                 ...                ...              ...            ...
9997                1.0                0.0              0.0            0.0
9998                0.0                1.0              0.0            0.0
9999                0.0                1.0              0.0            0.0
10000               1.0                0.0              0.0            0.0
10001               1.0                0.0              0.0            0.0

[10002 rows x 4 columns]

In [15]:
data_set = pd.concat([data_set.drop("Geography",axis=1), geo_encoded_df], axis=1)

In [16]:
data_set

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Geography_nan
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1.0,0.0,0.0,0.0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0.0,0.0,1.0,0.0
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1.0,0.0,0.0,0.0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1.0,0.0,0.0,0.0
4,850,0,43.0,2,125510.82,1,NaN,1.0,79084.10,0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9997,709,0,36.0,7,0.00,1,0.0,1.0,42085.58,1,1.0,0.0,0.0,0.0
9998,772,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0,0.0
9999,772,1,42.0,3,75075.31,2,1.0,0.0,92888.52,1,0.0,1.0,0.0,0.0
10000,792,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0,0.0
10001,792,0,28.0,4,130142.79,1,1.0,0.0,38190.78,0,1.0,0.0,0.0,0.0

In [17]:

# dividing the data with dependent and independent features

In [18]:
data_set.head(5)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Geography_nan
0,619,0,42.0,2,0.00,1,1.0,1.0,101348.88,1,1.0,0.0,0.0,0.0
1,608,0,41.0,1,83807.86,1,0.0,1.0,112542.58,0,0.0,0.0,1.0,0.0
2,502,0,42.0,8,159660.80,3,1.0,0.0,113931.57,1,1.0,0.0,0.0,0.0
3,699,0,39.0,1,0.00,2,0.0,0.0,93826.63,0,1.0,0.0,0.0,0.0
4,850,0,43.0,2,125510.82,1,NaN,1.0,79084.10,0,0.0,0.0,1.0,0.0

In [19]:
x = data_set.drop("Exited",axis=1)
y = data_set["Exited"]

In [20]:
# splinting the data into train and test
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
print(type(X_train))
print(type(X_test))

print(X_train.shape)
print(X_test.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(8001, 13)
(2001, 13)

In [22]:
# scaleing the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
X_train

array([[-0.19344335,  0.91360328,  0.29611233, ...,  1.72529422,
        -0.57710974, -0.01118034],
       [-0.95045188,  0.91360328, -1.42269719, ..., -0.57961128,
         1.73277271, -0.01118034],
       [ 0.10728607, -1.094567  , -0.84976068, ..., -0.57961128,
        -0.57710974, -0.01118034],
       ...,
       [ 0.87466458, -1.094567  , -0.08584534, ..., -0.57961128,
        -0.57710974, -0.01118034],
       [ 0.16950595,  0.91360328,  0.39160174, ..., -0.57961128,
        -0.57710974, -0.01118034],
       [ 0.48060534,  0.91360328,  1.15551708, ...,  1.72529422,
        -0.57710974, -0.01118034]], shape=(8001, 13))

# ------- #step :4 # ----------#

# ANN  impermentaion

In [24]:
pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\abhia\anaconda3\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (2.3.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (25.9.23)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (0.6.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (23.2)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (5.29.3)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (83.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (3.1.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (1.76.0)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (3.11.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (2.4.6)
Requirement already satisfied: h5py>=3.11.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\abhia\anaconda3\lib\site-packages (from tensorflow) (0.5.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\abhia\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\abhia\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\abhia\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abhia\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.7.14)
Requirement already satisfied: markdown>=2.6.8 in c:\users\abhia\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.8)
Requirement already satisfied: pillow in c:\users\abhia\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.1.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\abhia\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\abhia\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\abhia\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\abhia\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in c:\users\abhia\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\abhia\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\abhia\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\abhia\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\abhia\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\abhia\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.0)
Note: you may need to restart the kernel to use updated packages.

In [25]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [26]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping

In [27]:
# creating a model outline

In [28]:
model = Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
        Dense(32,activation='relu'),
        Dense(1,activation='sigmoid')
    ]
)

C:\Users\abhia\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

model.summary()

In [29]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:

import tensorflow as tf
opt = tf.keras.optimizers.Adam(learning_rate = 0.01)

In [31]:
# initilizing the loss and optimizers

In [32]:
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [33]:
# initlizing tenserboad

In [34]:
import tensorflow as tf
from tensorflow.keras.callbacks import TensorBoard

In [35]:
pip install datetime

Requirement already satisfied: datetime in c:\users\abhia\anaconda3\lib\site-packages (6.0)
Requirement already satisfied: zope.interface in c:\users\abhia\anaconda3\lib\site-packages (from datetime) (7.1.1)
Requirement already satisfied: pytz in c:\users\abhia\anaconda3\lib\site-packages (from datetime) (2024.1)
Requirement already satisfied: setuptools in c:\users\abhia\anaconda3\lib\site-packages (from zope.interface->datetime) (83.0.0)
Note: you may need to restart the kernel to use updated packages.

In [36]:
import datetime
from tensorflow.keras.callbacks import TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [37]:
# setuping the ealy  stopping technique

In [38]:
early_stopping = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [39]:
karthik_model = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
     callbacks = [tensorboard_callback,early_stopping]
)

Epoch 1/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.8120 - loss: 0.4640 - val_accuracy: 0.7991 - val_loss: 0.5024
Epoch 2/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7955 - loss: 0.5073 - val_accuracy: 0.7991 - val_loss: 0.5038
Epoch 3/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5077 - val_accuracy: 0.7991 - val_loss: 0.5035
Epoch 4/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7955 - loss: 0.5081 - val_accuracy: 0.7991 - val_loss: 0.5037
Epoch 5/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7955 - loss: 0.5086 - val_accuracy: 0.7991 - val_loss: 0.5017
Epoch 6/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5071 - val_accuracy: 0.7991 - val_loss: 0.5019
Epoch 7/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5077 - val_accuracy: 0.7991 - val_loss: 0.5024
Epoch 8/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5076 - val_accuracy: 0.7991 - val_loss: 0.5034
Epoch 9/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5080 - val_accuracy: 0.7991 - val_loss: 0.5028
Epoch 10/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5078 - val_accuracy: 0.7991 - val_loss: 0.5060
Epoch 11/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5089 - val_accuracy: 0.7991 - val_loss: 0.5018
Epoch 12/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5077 - val_accuracy: 0.7991 - val_loss: 0.5034
Epoch 13/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5077 - val_accuracy: 0.7991 - val_loss: 0.5035
Epoch 14/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5073 - val_accuracy: 0.7991 - val_loss: 0.5025
Epoch 15/100
251/251 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7955 - loss: 0.5074 - val_accuracy: 0.7991 - val_loss: 0.5020

In [40]:
model.save("model.keras")

In [41]:
new_data = [[
    600,    # CreditScore
    1,      # Gender (Male=1, Female=0)
    40,     # Age
    3,      # Tenure
    60000,  # Balance
    2,      # NumOfProducts
    1,      # HasCrCard
    1,      # IsActiveMember
    50000,  # EstimatedSalary
    1,      # Geography_France
    0,      # Geography_Germany
    0, 
    0# Geography_Spain
]]

In [42]:
new_data_scaled = scaler.transform(new_data)

C:\Users\abhia\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [43]:
prediction = model.predict(new_data_scaled)
print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step
[[0.1989889]]

In [44]:
if prediction[0][0] > 0.5:
    print("Customer will leave the bank.")
else:
    print("Customer will stay with the bank.")

Customer will stay with the bank.

# but i want take input from the user

In [ ]:
import numpy as np

# ---------- Take Input ----------
CreditScore = float(input("Enter Credit Score: "))
Geography = input("Enter Geography (France/Germany/Spain): ")
Gender = input("Enter Gender (Male/Female): ")
Age = int(input("Enter Age: "))
Tenure = int(input("Enter Tenure: "))
Balance = float(input("Enter Balance: "))
NumOfProducts = int(input("Enter Number of Products: "))
HasCrCard = int(input("Has Credit Card? (1 = Yes, 0 = No): "))
IsActiveMember = int(input("Is Active Member? (1 = Yes, 0 = No): "))
EstimatedSalary = float(input("Enter Estimated Salary: "))

# ---------- Encode Gender ----------
gender_encoded = LB.transform([Gender])[0]

# ---------- Encode Geography ----------
geo_encoded = onehot_encoder_geo.transform([[Geography]]).toarray()

# ---------- Create Input ----------
new_data = np.array([[
    CreditScore,
    gender_encoded,
    Age,
    Tenure,
    Balance,
    NumOfProducts,
    HasCrCard,
    IsActiveMember,
    EstimatedSalary
]])

# ---------- Add Geography Columns ----------
new_data = np.concatenate((new_data, geo_encoded), axis=1)

# ---------- Scale ----------
new_data = scaler.transform(new_data)

# ---------- Predict ----------
prediction = model.predict(new_data)

print("\nPrediction Probability:", prediction[0][0])

if prediction[0][0] >= 0.5:
    print("Customer is likely to LEAVE the bank.")
else:
    print("Customer is likely to STAY with the bank.")